### PR TITLE
Fix little error

### PR DESCRIPTION
**Pull request by vladd12**
When I was implementing the algorithm in my project, I saw this error

### CODE REVIEW

**Comment by Medik-GH** [comment]
I completely missed this @vladd12, my apologies. Can you explain why this is an error? It's been a long time since I looked at this code ^^

**Comment by vladd12** [comment]
@EddieEldridge
> I completely missed this @vladd12, my apologies. Can you explain why this is an error? It's been a long time since I looked at this code ^^

This is not a mistake, but a typo. In the comment line above for a init byte specified 0x80 value, not 0x01, so I thought it as a typo

**Comment by Medik-GH** [comment]
I understand, well if you are sure there is a bug in the code, I'm happy to merge but for the time being I'd assume the **comment** is incorrect and the **code** is correct as right now it correctly evaluates the hashes for the given strings.

**Comment by vladd12** [comment]
@EddieEldridge I'm sorry, maybe I incorrect understand the code and comments, but with this change I was getting correct string hashes for strings that presented in readme file (and more other). I'm not sure, but it's possible that that instruction are never executed.

**Comment by Medik-GH** [comment]
@vladd12 Okay, sounds good, perhaps I never tested the PAD1 condition. I will merge, thank you very much!

**Pull request merged**
